# Generated by Django 5.1.2 on 2024-11-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0002_user_user_type"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authy.business",
            ),
        ),
    ]
