# Generated by Django 5.1.2 on 2024-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.TextField(
                choices=[("client", "client"), ("enterprise", "enterprise")],
                default="client",
            ),
        ),
    ]
